<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>IndexShelf.Application.Abstractions</RootNamespace>
    <AssemblyName>IndexShelf.Application.Abstractions</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IndexShelf.SharedKernel\IndexShelf.SharedKernel.csproj" />
  </ItemGroup>
</Project>
